# Generated by Django 3.1.7 on 2021-03-19 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
                ('WIJHARS', models.CharField(default='', max_length=100)),
                ('assortment', models.CharField(default='', max_length=100)),
                ('admission_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
