# Generated by Django 3.1.7 on 2021-03-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
