# Generated by Django 3.1.7 on 2021-04-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('Control type', 'Typ kontroli'), ('Metod and norm', 'Norma i metoda pobrania'), ('Research status', 'Status badania'), ('Research', 'Badanie'), ('Sampling', 'Próbka'), ('Type', 'Typ'), ('Wijhars', 'WIJHARS')], default='', max_length=100)),
                ('mode', models.CharField(choices=[('Write', 'Zapisz do csv'), ('Read', 'Odczytaj z csv')], default='Write', max_length=100)),
            ],
        ),
    ]
