# Generated by Django 3.1.7 on 2021-03-20 00:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WIJHARS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
                ('assortment', models.CharField(max_length=100)),
                ('admission_date', models.DateField(default=datetime.date.today)),
                ('expiration_date', models.DateField()),
                ('completion_date', models.DateField(help_text='Select a date')),
                ('additional_comment', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('condition', models.CharField(default='Bez zastrzeżeń', max_length=100)),
                ('appeal_analysis', models.BooleanField(default=True)),
                ('control_type', models.CharField(max_length=100)),
                ('sampling_method', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('WIJHARS', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.wijhars')),
            ],
        ),
    ]
