# Generated by Django 3.1.7 on 2021-05-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampling',
            options={'permissions': [('can_operate_on_sampling', 'Can add/edit/delete sampling')]},
        ),
    ]
