# Generated by Django 3.1.7 on 2021-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampling',
            name='agreement_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampling',
            name='batch_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampling',
            name='batch_production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampling',
            name='batch_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampling',
            name='case_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampling',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampling',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampling',
            name='recipient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sampling',
            name='type_of_package',
            field=models.TextField(blank=True, null=True),
        ),
    ]
