# Generated by Django 3.1.7 on 2021-05-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='completion_date',
            new_name='research_completion_date',
        ),
    ]
