# Generated by Django 3.1.7 on 2021-05-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20210503_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampling',
            name='agreement_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sampling',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sampling',
            name='batch_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sampling',
            name='case_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sampling',
            name='recipient',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sampling',
            name='type_of_package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
