# Generated by Django 3.1.7 on 2021-05-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20210510_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='result',
            field=models.CharField(max_length=200),
        ),
    ]
