# Generated by Django 3.1.7 on 2021-05-09 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20210509_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindControlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.controltype')),
            ],
        ),
    ]
