# Generated by Django 3.1.7 on 2021-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20210503_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sampling',
            name='batch_production_date',
            field=models.DateField(null=True),
        ),
    ]
