# Generated by Django 3.1.7 on 2021-03-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20210320_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='appeal_analysis',
            field=models.BooleanField(default=False),
        ),
    ]
