# Generated by Django 3.1.7 on 2021-05-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_findcontroltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindWIJHARS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wijhars_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.wijhars')),
            ],
        ),
        migrations.CreateModel(
            name='FindType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.type')),
            ],
        ),
        migrations.CreateModel(
            name='FindResearchStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_status_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.researchstatus')),
            ],
        ),
        migrations.CreateModel(
            name='FindMetodAndNorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metod_and_norm_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.metodandnorm')),
            ],
        ),
        migrations.CreateModel(
            name='FindDeliveryWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_way_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.deliveryway')),
            ],
        ),
    ]
