# Generated by Django 3.1.7 on 2021-03-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20210331_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='summary_requirements_explains',
            field=models.TextField(blank=True),
        ),
    ]
