# Generated by Django 3.1.7 on 2021-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20210510_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='requirementsType',
            field=models.CharField(choices=[('law', 'np.norm, przepisów prawa1'), ('specification', 'np.Specyfikacji jakościowej'), ('producent', 'np. oznakowania producenta...')], default='law', max_length=200),
            preserve_default=False,
        ),
    ]
