# Generated by Django 3.1.7 on 2021-05-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_finddeliveryway_findmetodandnorm_findresearchstatus_findtype_findwijhars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controltype',
            options={'permissions': [('can_operate_on_ControlType', 'Can add/edit/delete ControlType')]},
        ),
        migrations.AlterModelOptions(
            name='deliveryway',
            options={'permissions': [('can_operate_on_DeliveryWay', 'Can add/edit/delete DeliveryWay')]},
        ),
        migrations.AlterModelOptions(
            name='metodandnorm',
            options={'permissions': [('can_operate_on_MetodAndNorm', 'Can add/edit/delete MetodAndNorm')]},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'permissions': [('can_operate_on_Research', 'Can add/edit/delete Research')]},
        ),
        migrations.AlterModelOptions(
            name='researchstatus',
            options={'permissions': [('can_operate_on_ResearchStatus', 'Can add/edit/delete ResearchStatus')]},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'permissions': [('can_operate_on_Type', 'Can add/edit/delete Type')]},
        ),
        migrations.AlterModelOptions(
            name='wijhars',
            options={'permissions': [('can_operate_on_WIJHARS', 'Can add/edit/delete WIJHARS')]},
        ),
    ]
