# Generated by Django 3.1.7 on 2021-05-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20210503_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='completion_date',
            new_name='research_completion_date',
        ),
    ]
